class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'series_title': 'Series Title',
      'category': 'Category',
      'type': 'Type',
      'method_of_attack': 'Method of Attack',
      'moves': 'moves',
      'punches': 'Punches',
      'kicks': 'Kicks',
      'packs': 'Packs',
      'trapping': 'Trapping',
      'move': 'Move',
      'jkd_moves': 'JKD Moves',
      'general': 'General',
      'other': 'Other',
      'left': 'Left',
      'right': 'Right',
      'high': 'High',
      'mid': 'Mid',
      'low': 'Low',
      'draw': 'Draw',
      'current_combo': 'CURRENT COMBO',
      'finish_combo': 'Finish Combo',
      'next': 'Next',
      'answer': 'Answer',
      'finish': 'Finish',
      'cancel': 'Cancel',
      'update_item': 'Update',
      'configure': 'Configure',
      'add': 'Add',
      'library_title': 'JKD',
      'new_series': 'New Series',
      'no_series': 'No series in',
      'pick_answer': 'Pick Answer Move',
      'notes': 'Notes',
      'method': 'Method',
      'reps': 'Repetitions',
      'move_setup': 'Move Setup',
      'nothing': 'Nothing',
      'delete_series': 'Delete Series',
      'delete_item': 'Delete Item',
      'confirm_delete': 'Are you sure you want to delete',
      'confirm_delete_item': 'Are you sure you want to delete this item?',
      'training_starts_in': 'Training starts in',
      'backup_export': 'Series Backup & Export',
      'export_desc': 'Export your series to JSON files',
      'export_title': 'Select what to export',
      'export_all': 'Everything (All Categories)',
      'export_category': 'Entire Category',
      'export_single': 'Single Series',
      'export_success': 'Exported successfully to',
      'export_error': 'Failed to export',
      'share': 'Share',
      'share_json': 'Share JSON',
      'save_to_device': 'Save to Device',
      'select_series': 'Select Series',
      'import_series': 'Import Series',
      'import_desc': 'Import series from a JSON file',
      'import_success': 'Imported successfully!',
      'import_error': 'Failed to import file',
      'no_file_selected': 'No file selected',
      'theme': 'Theme',
      'theme_color': 'Theme Color',
      'view_logs': 'View Logs',
      'logs_title': 'Application Logs',
      'save_logs': 'Save Logs',
      'logs_saved': 'Logs saved to',
      'system_theme': 'System',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'amoled_theme': 'AMOled Dark',
      'language': 'Language',
      'search_hint': 'Search...',
      'no_results': 'No series found matching your search.',
      'export_to_pdf': 'Export to PDF',
      'training_mode': 'Training Mode',
      'interval': 'Interval (sec)',
      'combo_interval': 'Combo Interval (ms)',
      'start': 'Start',
      'stop': 'Stop',
      'training_desc': 'The app will read each move aloud.',
      'gallery_path': 'Gallery Storage Folder',
      'select_folder': 'Select Folder',
      'no_images': 'No images found for this move.',
      'instructional_photos': 'Instructional Photos',
      'capture_photo': 'Take Photo',
      'processing': 'Processing image...',
      'clone': 'Clone',
      'cloned': 'cloned',
      'manage_series': 'Manage Series Developer',
      'manage_series_desc':
          'Enable cloning, deleting and advanced synchronization',
      'expert_mode': 'Expert Mode',
      'media_backup': 'Media Backup (ZIP)',
      'backup_images': 'Backup All Images',
      'restore_images': 'Restore Images (ZIP)',
      'backup_success': 'Backup created at',
      'restore_success': 'Images restored successfully!',
      'voice_recognition': 'Voice Recognition (Experimental)',
      'voice_notes': 'Voice Notes',
      'record': 'Record',
      'play': 'Play',
      'rename': 'Rename',
      'delete': 'Delete',
      'new_recording': 'New Recording',
      'backup_glossary': 'Backup Glossary',
      'restore_glossary': 'Restore Glossary',
      'glossary_backup_desc': 'Export your entire glossary to JSON',
      'glossary_restore_desc': 'Import glossary from JSON (Overwrites current)',
      'reset_database': 'Reset Database',
      'reset_database_desc': 'Reset database to factory defaults',
      'reset_db_title': 'Reset Database',
      'reset_db_warning':
          'WARNING: This will DELETE ALL your data and restore the database to factory defaults with system series only. This action CANNOT be undone!',
      'reset_db_confirm': 'Are you absolutely sure?',
      'reset_db_success': 'Database reset successfully',
      'error': 'Error',
      'voice_help_title': 'Voice Input Help',
      'edit': 'Edit',
      'hit': 'Hit',
      'speech_rate': 'Speech Rate',
      'series_added': 'Series added successfully!',
      'series_updated': 'Series updated successfully!',
      'confirm_clone': 'Are you sure you want to clone this series?',
      'training_programs': 'Training Programs',
      'active_training': 'Active Training',
      'no_active_training':
          'No active training program. Select a program from the Training Programs tab to start.',
      'all': 'All',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'days': 'days',
      'day': 'Day',
      'resume': 'Resume',
      'warning': 'Warning',
      'abandon': 'Abandon',
      'abandon_current_program':
          'You already have an active program. Abandon current program first?',
      'program_started': 'Program started successfully!',
      'no_programs_found': 'No programs found',
      'progress': 'Progress',
      'daily_schedule': 'Daily Schedule',
      'start_program': 'Start Program',
      'abandon_program': 'Abandon Program',
      'abandon_program_confirm':
          'Are you sure you want to abandon this program? Your progress will be lost.',
      'rest_day': 'Rest Day',
      'create_program': 'Create Program',
      'edit_program': 'Edit Program',
      'program_title': 'Program Title',
      'program_description': 'Program Description',
      'difficulty': 'Difficulty',
      'add_series': 'Add Series',
      'items_range': 'Items Range',
      'practice_all_items': 'Practice all items',
      'from': 'From',
      'to': 'To',
      'assigned_series': 'Assigned Series',
      'daily_config': 'Daily Schedule Configuration',
      'export_json': 'Export JSON',
      'show_translation': 'Show Translation',
      'show_translation_desc': 'Display translation below each action',
    },
    'fr': {
      'series_title': 'Titre de la série',
      'category': 'Catégorie',
      'type': 'Type',
      'method_of_attack': 'Méthode d\'attaque',
      'moves': 'mouvements',
      'punches': 'Coups de poing',
      'kicks': 'Coups de pied',
      'packs': 'Packs',
      'trapping': 'Trapping',
      'move': 'Déplacement',
      'jkd_moves': 'Déplacements JKD',
      'general': 'Général',
      'other': 'Autre',
      'left': 'Gauche',
      'right': 'Droite',
      'high': 'Haut',
      'mid': 'Centre',
      'low': 'Bas',
      'draw': 'Feinte',
      'current_combo': 'COMBO ACTUEL',
      'finish_combo': 'Terminer le Combo',
      'next': 'Suivant',
      'answer': 'Réponse',
      'finish': 'Terminer',
      'cancel': 'Annuler',
      'update_item': 'Mettre à jour',
      'configure': 'Configurer',
      'add': 'Ajouter',
      'library_title': 'JKD',
      'new_series': 'Nouvelle Série',
      'no_series': 'Aucune série dans',
      'pick_answer': 'Choisir une réponse',
      'notes': 'Notes',
      'method': 'Méthode',
      'reps': 'Répétitions',
      'move_setup': 'Configuration du mouvement',
      'nothing': 'Rien',
      'delete_series': 'Supprimer la série',
      'delete_item': 'Supprimer l\'item',
      'confirm_delete': 'Êtes-vous sûr de vouloir supprimer',
      'confirm_delete_item': 'Êtes-vous sûr de vouloir supprimer cet item ?',
      'training_starts_in': 'L\'entraînement commence dans',
      'backup_export': 'Sauvegarde & Export des Séries',
      'export_desc': 'Exporter vos séries en fichiers JSON',
      'export_title': 'Sélectionnez quoi exporter',
      'export_all': 'Tout (Toutes les catégories)',
      'export_category': 'Catégorie entière',
      'export_single': 'Une seule série',
      'export_success': 'Exporté avec succès vers',
      'export_error': 'Échec de l\'exportation',
      'share': 'Partager',
      'share_json': 'Partager JSON',
      'save_to_device': 'Enregistrer sur l\'appareil',
      'select_series': 'Sélectionner une série',
      'import_series': 'Importer des Séries',
      'import_desc': 'Importer des séries depuis un fichier JSON',
      'import_success': 'Importation réussie !',
      'import_error': 'Échec de l\'importation du fichier',
      'no_file_selected': 'Aucun fichier sélectionné',
      'theme': 'Thème',
      'theme_color': 'Couleur du thème',
      'view_logs': 'Voir les logs',
      'logs_title': 'Logs de l\'application',
      'save_logs': 'Enregistrer les logs',
      'logs_saved': 'Logs enregistrés dans',
      'system_theme': 'Système',
      'light_theme': 'Clair',
      'dark_theme': 'Sombre',
      'amoled_theme': 'AMOled Noir',
      'language': 'Langue',
      'search_hint': 'Rechercher...',
      'no_results': 'Aucune série ne correspond à votre recherche.',
      'export_to_pdf': 'Exporter en PDF',
      'training_mode': 'Mode Entraînement',
      'interval': 'Intervalle (sec)',
      'combo_interval': 'Intervalle Combo (ms)',
      'start': 'Démarrer',
      'stop': 'Arrêter',
      'training_desc': 'L\'application va lire chaque mouvement à voix haute.',
      'gallery_path': 'Dossier de stockage de la galerie',
      'select_folder': 'Choisir un dossier',
      'no_images': 'Aucune image trouvée pour ce mouvement.',
      'instructional_photos': 'Photos pédagogiques',
      'capture_photo': 'Prendre une photo',
      'processing': 'Traitement de l\'image...',
      'clone': 'Cloner',
      'cloned': 'copie',
      'manage_series': 'Gérer les séries Developer',
      'manage_series_desc':
          'Activer le clonage, la suppression et la synchronisation avancée',
      'expert_mode': 'Mode Expert',
      'media_backup': 'Sauvegarde Médias (ZIP)',
      'backup_images': 'Sauvegarder toutes les images',
      'restore_images': 'Restaurer les images (ZIP)',
      'backup_success': 'Sauvegarde créée à',
      'restore_success': 'Images restaurées avec succès !',
      'voice_recognition': 'Reconnaissance vocale (Expérimental)',
      'voice_notes': 'Notes Vocales',
      'record': 'Enregistrer',
      'play': 'Jouer',
      'rename': 'Renommer',
      'delete': 'Supprimer',
      'new_recording': 'Nouvel Enregistrement',
      'backup_glossary': 'Sauvegarder le Glossaire',
      'restore_glossary': 'Restaurer le Glossaire',
      'glossary_backup_desc': 'Exporter tout votre glossaire en JSON',
      'glossary_restore_desc': 'Importer le glossaire (Écrase l\'actuel)',
      'reset_database': 'Réinitialiser la Base de Données',
      'reset_database_desc': 'Réinitialiser la base aux paramètres d\'usine',
      'reset_db_title': 'Réinitialiser la Base de Données',
      'reset_db_warning':
          'ATTENTION : Cela va SUPPRIMER TOUTES vos données et restaurer la base aux paramètres d\'usine avec uniquement les séries système. Cette action NE PEUT PAS être annulée !',
      'reset_db_confirm': 'Êtes-vous absolument sûr ?',
      'reset_db_success': 'Base de données réinitialisée avec succès',
      'error': 'Erreur',
      'voice_help_title': 'Aide Saisie Vocale',
      'edit': 'Modifier',
      'hit': 'Attaque',
      'speech_rate': 'Vitesse de lecture',
      'series_added': 'Série ajoutée avec succès !',
      'series_updated': 'Série mise à jour avec succès !',
      'confirm_clone': 'Êtes-vous sûr de vouloir cloner cette série ?',
      'training_programs': 'Programmes d\'Entraînement',
      'active_training': 'Entraînement Actif',
      'no_active_training':
          'Aucun programme actif. Sélectionnez un programme dans l\'onglet "Programmes d\'Entraînement" pour commencer.',
      'all': 'Tous',
      'beginner': 'Débutant',
      'intermediate': 'Intermédiaire',
      'advanced': 'Avancé',
      'days': 'jours',
      'day': 'Jour',
      'resume': 'Reprendre',
      'warning': 'Attention',
      'abandon': 'Abandonner',
      'abandon_current_program':
          'Vous avez déjà un programme actif. Abandonner le programme actuel d\'abord ?',
      'program_started': 'Programme démarré avec succès !',
      'no_programs_found': 'Aucun programme trouvé',
      'progress': 'Progrès',
      'daily_schedule': 'Programme Quotidien',
      'start_program': 'Démarrer le Programme',
      'abandon_program': 'Abandonner le Programme',
      'abandon_program_confirm':
          'Êtes-vous sûr de vouloir abandonner ce programme ? Votre progrès sera perdu.',
      'rest_day': 'Jour de Repos',
      'create_program': 'Créer un Programme',
      'edit_program': 'Modifier le Programme',
      'program_title': 'Titre du Programme',
      'program_description': 'Description du Programme',
      'difficulty': 'Difficulté',
      'add_series': 'Ajouter une Série',
      'items_range': 'Plage d\'Items',
      'practice_all_items': 'Pratiquer tous les items',
      'from': 'De',
      'to': 'À',
      'assigned_series': 'Séries Assignées',
      'daily_config': 'Configuration du Programme Quotidien',
      'export_json': 'Exporter JSON',
      'show_translation': 'Afficher la Traduction',
      'show_translation_desc': 'Afficher la traduction sous chaque action',
    },
  };

  static String translate(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
