class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'series_title': 'Series Title',
      'category': 'Category',
      'type': 'Type',
      'method_of_attack': 'Method of Attack',
      'moves': 'moves',
      'punches': 'Punches',
      'kicks': 'Kicks',
      'packs': 'Packs',
      'trapping': 'Trapping',
      'special': 'Move',
      'general': 'General',
      'other': 'Other',
      'left': 'Left',
      'right': 'Right',
      'high': 'High',
      'mid': 'Mid',
      'low': 'Low',
      'draw': 'Draw',
      'current_combo': 'CURRENT COMBO',
      'finish_combo': 'Finish Combo',
      'next': 'Next',
      'answer': 'Answer',
      'finish': 'Finish',
      'cancel': 'Cancel',
      'update_item': 'Update',
      'configure': 'Configure',
      'add': 'Add',
      'library_title': 'Jeet Kune Do Notes',
      'new_series': 'New Series',
      'no_series': 'No series in',
      'pick_answer': 'Pick Answer Move',
      'notes': 'Notes',
      'method': 'Method',
      'reps': 'Repetitions',
      'move_setup': 'Move Setup',
      'nothing': 'Nothing',
      'delete_series': 'Delete Series',
      'delete_item': 'Delete Item',
      'confirm_delete': 'Are you sure you want to delete',
      'confirm_delete_item': 'Are you sure you want to delete this item?',
      'training_starts_in': 'Training starts in',
      'backup_export': 'Series Backup & Export',
      'export_desc': 'Export your series to JSON files',
      'export_title': 'Select what to export',
      'export_all': 'Everything (All Categories)',
      'export_category': 'Entire Category',
      'export_single': 'Single Series',
      'export_success': 'Exported successfully to',
      'export_error': 'Failed to export',
      'select_series': 'Select Series',
      'import_series': 'Import Series',
      'import_desc': 'Import series from a JSON file',
      'import_success': 'Imported successfully!',
      'import_error': 'Failed to import file',
      'no_file_selected': 'No file selected',
      'theme': 'Theme',
      'system_theme': 'System Theme',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'amoled_theme': 'AMOled Dark',
      'language': 'Language',
      'search_hint': 'Search...',
      'no_results': 'No series found matching your search.',
      'export_to_pdf': 'Export to PDF',
      'training_mode': 'Training Mode',
      'interval': 'Interval (sec)',
      'start': 'Start',
      'stop': 'Stop',
      'training_desc': 'The app will read each move aloud.',
      'gallery_path': 'Gallery Storage Folder',
      'select_folder': 'Select Folder',
      'no_images': 'No images found for this move.',
      'instructional_photos': 'Instructional Photos',
      'capture_photo': 'Take Photo',
      'processing': 'Processing image...',
      'clone': 'Clone',
      'cloned': 'cloned',
      'expert_mode': 'Expert Mode',
      'media_backup': 'Media Backup (ZIP)',
      'backup_images': 'Backup All Images',
      'restore_images': 'Restore Images (ZIP)',
      'backup_success': 'Backup created at',
      'restore_success': 'Images restored successfully!',
      'voice_recognition': 'Voice Recognition (Experimental)',
      'voice_notes': 'Voice Notes',
      'record': 'Record',
      'play': 'Play',
      'rename': 'Rename',
      'delete': 'Delete',
      'new_recording': 'New Recording',
      'backup_glossary': 'Backup Glossary',
      'restore_glossary': 'Restore Glossary',
      'glossary_backup_desc': 'Export your entire glossary to JSON',
      'glossary_restore_desc': 'Import glossary from JSON (Overwrites current)',
      'error': 'Error',
      'voice_help_title': 'Voice Input Help',
      'edit': 'Edit',
      'hit': 'Hit',
      'speech_rate': 'Speech Rate',
    },
    'fr': {
      'series_title': 'Titre de la série',
      'category': 'Catégorie',
      'type': 'Type',
      'method_of_attack': 'Méthode d\'attaque',
      'moves': 'mouvements',
      'punches': 'Coups de poing',
      'kicks': 'Coups de pied',
      'packs': 'Packs',
      'trapping': 'Trapping',
      'special': 'Déplacement',
      'general': 'Général',
      'other': 'Autre',
      'left': 'Gauche',
      'right': 'Droite',
      'high': 'Haut',
      'mid': 'Centre',
      'low': 'Bas',
      'draw': 'Feinte',
      'current_combo': 'COMBO ACTUEL',
      'finish_combo': 'Terminer le Combo',
      'next': 'Suivant',
      'answer': 'Réponse',
      'finish': 'Terminer',
      'cancel': 'Annuler',
      'update_item': 'Mettre à jour',
      'configure': 'Configurer',
      'add': 'Ajouter',
      'library_title': 'Jeet Kune Do Notes',
      'new_series': 'Nouvelle Série',
      'no_series': 'Aucune série dans',
      'pick_answer': 'Choisir une réponse',
      'notes': 'Notes',
      'method': 'Méthode',
      'reps': 'Répétitions',
      'move_setup': 'Configuration du mouvement',
      'nothing': 'Rien',
      'delete_series': 'Supprimer la série',
      'delete_item': 'Supprimer l\'item',
      'confirm_delete': 'Êtes-vous sûr de vouloir supprimer',
      'confirm_delete_item': 'Êtes-vous sûr de vouloir supprimer cet item ?',
      'training_starts_in': 'L\'entraînement commence dans',
      'backup_export': 'Sauvegarde & Export des Séries',
      'export_desc': 'Exporter vos séries en fichiers JSON',
      'export_title': 'Sélectionnez quoi exporter',
      'export_all': 'Tout (Toutes les catégories)',
      'export_category': 'Catégorie entière',
      'export_single': 'Une seule série',
      'export_success': 'Exporté avec succès vers',
      'export_error': 'Échec de l\'exportation',
      'select_series': 'Sélectionner une série',
      'import_series': 'Importer des Séries',
      'import_desc': 'Importer des séries depuis un fichier JSON',
      'import_success': 'Importation réussie !',
      'import_error': 'Échec de l\'importation du fichier',
      'no_file_selected': 'Aucun fichier sélectionné',
      'theme': 'Thème',
      'system_theme': 'Thème Système',
      'light_theme': 'Clair',
      'dark_theme': 'Sombre',
      'amoled_theme': 'AMOled Noir',
      'language': 'Langue',
      'search_hint': 'Rechercher...',
      'no_results': 'Aucune série ne correspond à votre recherche.',
      'export_to_pdf': 'Exporter en PDF',
      'training_mode': 'Mode Entraînement',
      'interval': 'Intervalle (sec)',
      'start': 'Démarrer',
      'stop': 'Arrêter',
      'training_desc': 'L\'application va lire chaque mouvement à voix haute.',
      'gallery_path': 'Dossier de stockage de la galerie',
      'select_folder': 'Choisir un dossier',
      'no_images': 'Aucune image trouvée pour ce mouvement.',
      'instructional_photos': 'Photos pédagogiques',
      'capture_photo': 'Prendre une photo',
      'processing': 'Traitement de l\'image...',
      'clone': 'Cloner',
      'cloned': 'copie',
      'expert_mode': 'Mode Expert',
      'media_backup': 'Sauvegarde Médias (ZIP)',
      'backup_images': 'Sauvegarder toutes les images',
      'restore_images': 'Restaurer les images (ZIP)',
      'backup_success': 'Sauvegarde créée à',
      'restore_success': 'Images restaurées avec succès !',
      'voice_recognition': 'Reconnaissance vocale (Expérimental)',
      'voice_notes': 'Notes Vocales',
      'record': 'Enregistrer',
      'play': 'Jouer',
      'rename': 'Renommer',
      'delete': 'Supprimer',
      'new_recording': 'Nouvel Enregistrement',
      'backup_glossary': 'Sauvegarder le Glossaire',
      'restore_glossary': 'Restaurer le Glossaire',
      'glossary_backup_desc': 'Exporter tout votre glossaire en JSON',
      'glossary_restore_desc': 'Importer le glossaire (Écrase l\'actuel)',
      'error': 'Erreur',
      'voice_help_title': 'Aide Saisie Vocale',
      'edit': 'Modifier',
      'hit': 'Attaque',
      'speech_rate': 'Vitesse de lecture',
    },
  };

  static String translate(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
